config/routes.rb
UKETSUKERUDAY::Application.routes.draw do
	resources :participants

  root :to => 'participants#index'

end

app/models/participant.rb
class Participant < ActiveRecord::Base
	module Arrival; end
	Arrival::YET = 0
	Arrival::ARRIVED = 1

	ARRIVAL_NAME = {
		Arrival::YET => "KITENAI",
		Arrival::ARRIVED => "KITERU"
	}

	module Occupation; end
	Occupation::STUDENT = 0
	Occupation::WORKER = 1

	OCCUPATION_NAME = {
    Occupation::STUDENT => "student",
    Occupation::WORKER => "worker"
	}

  def arrived?
    ARRIVAL_NAME[arrival]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all

    @students = Participant.where(occupation: Participant::Occupation::STUDENT)
    @workers = Participant.where(occupation: Participant::Occupation::WORKER)
    @arrived = Participant.where(arrival: Participant::Arrival::ARRIVED).count
    @notyet = Participant.where(arrival: Participant::Arrival::YET).count

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @participants }
    end
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
    @participant = Participant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/new
  # GET /participants/new.json
  def new
    @participant = Participant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/1/edit
  def edit
    @participant = Participant.find(params[:id])
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(params[:participant])

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render json: @participant, status: :created, location: @participant }
      else
        format.html { render action: "new" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /participants/1
  # PUT /participants/1.json
  def update
    @participant = Participant.find(params[:id])

    respond_to do |format|
      if @participant.update_attributes(params[:participant])
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy

    respond_to do |format|
      format.html { redirect_to participants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "UKETSUKERUDAY" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">UKETSUKERUDAY</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/participants/_form.html.erb
<%= form_for(@participant) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% @participant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label '名前' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label '来た？' %><br />
	<%= f.radio_button :arrival, "0" %> 来てない
	<%= f.radio_button :arrival, "1" %> 来た
  </div>
  <div class="field">
    <%= f.label '懇親会' %><br />
	<%= f.radio_button :BINGO, "0" %> 不参加
	<%= f.radio_button :BINGO, "1" %> 参加
  </div>
  <div class="field">
    <%= f.label '二次会' %><br />
	<%= f.radio_button :party, "0" %> 不参加
	<%= f.radio_button :party, "1" %> 参加
  </div>
  <div class="field">
    <%= f.label '職業' %><br />
	<%= f.radio_button :occupation, "0" %> 学生
	<%= f.radio_button :occupation, "1" %> 社会人
  </div>
  <div class="field">
    <%= f.label '備考' %><br />
    <%= f.text_area :remarks, :size=>"50x3" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<h1>カンファ本会参加予定者一覧</h1>
<div class="row">
  <div class="span12">
    <table>
      <tr>
        <th>きてます！</th>
        <th class="yet">まだです！</th>
      </tr>
      <tr>
        <th><%= @arrived %></th>
        <th><%= @notyet %></th>
      </tr>
    </table>
    <%= link_to '参加者登録', new_participant_path %>
    <h2>学生</h2>
    <table>
      <tr>
        <th>Name</th>
        <th></th>
      </tr>
      <% @students.each do |student| %>
        <% if student.arrival == 0 %>
          <tr class="yet">
        <% else %>
          <tr class="arrived">
        <% end %>
            <td><%= link_to student.name, edit_participant_path(student) %></td>
            <td><%= link_to 'delete', student, confirm: 'Are you sure?', method: :delete %></td>
          </tr>
      <% end %>
    </table>
    <br />
    <h2>社会人</h2>
    <table>
      <tr>
        <th>Name</th>
        <th></th>
      </tr>
      <% @workers.each do |worker| %>
        <% if worker.arrival == 0 %>
          <tr class="yet">
        <% else %>
          <tr class="arrived">
        <% end %>
            <td><%= link_to worker.name, edit_participant_path(worker) %></td>
            <td><%= link_to 'Destroy', worker, confirm: 'Are you sure?', method: :delete %></td>
          </tr>
      <% end %>
    </table>

app/views/participants/new.html.erb
<h1>参加者登録</h1>

<%= render 'form' %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @participant.name %>
</p>

<p>
  <b>Arrival:</b>
  <%= @participant.arrival %>
</p>

<p>
  <b>Bingo:</b>
  <%= @participant.BINGO %>
</p>

<p>
  <b>Party:</b>
  <%= @participant.party %>
</p>

<p>
  <b>Occupation:</b>
  <%= @participant.occupation %>
</p>

<p>
  <b>Remarks:</b>
  <%= @participant.remarks %>
</p>


<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>